# -*- coding: utf-8 -*-
"""basecodepy_test.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QVNTEJHPAsiPIqiJw5s56qGNThUoKpxS
"""

#py 확장자로 테스트 - 베이스코드